#!/usr/bin/env python3
// list all databases in mongoDB.
import pymongo

client = pymongo.MongoClient("mongodb://localhost:27017/")

print("Databases:")
for db_name in client.list_database_names():
    print(db_name)